Software-Technologies/ASP.NET-MVC/Exam/ForumSystem-master/Source/Web/ForumSystem.Web/ViewModels/Home/IndexBlogPostViewModel.cs
namespace ForumSystem.Web.ViewModels.Home
{
    using System;
    using System.Collections.Generic;
    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure.Mapping;

    public class IndexBlogPostViewModel : IMapFrom<Post>
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public User Author { get; set; }

        public DateTime CreatedOn { get; set; }

        public ICollection<Tag> Tags { get; set; }
    }
}

Software-Technologies/ASP.NET-MVC/Exam/ForumSystem-master/Source/Web/ForumSystem.Web/Controllers/HomeController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.Common.Repository;
    using ForumSystem.Data.Models;
    using ForumSystem.Web.ViewModels.Home;

    public class HomeController : Controller
    {
        private readonly IDeletableEntityRepository<Post> posts;

        public HomeController(IDeletableEntityRepository<Post> posts)
        {
            this.posts = posts;
        }

        public ActionResult Index()
        {
            var model = this.posts
                .All()
                .OrderByDescending(m => m.CreatedOn)
                .Project()
                .To<IndexBlogPostViewModel>();

            return this.View(model);
        }
    }
}

Software-Technologies/ASP.NET-MVC/Exam/ForumSystem-master/Source/Web/ForumSystem.Web/Controllers/VotesController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Web.Mvc;
    using ForumSystem.Data.Common.Repository;
    using ForumSystem.Data.Models;

    public class VotesController : Controller
    {
        private readonly IDeletableEntityRepository<Post> posts;

        public VotesController(IDeletableEntityRepository<Post> posts)
        {
            this.posts = posts;
        }

        public ActionResult PostVote()
        {
            return null;
        }

        public ActionResult VoteUp(int id)
        {
            return null;
        }

        public ActionResult VoteDown(int id)
        {
            return null;
        }
    }
}

Software-Technologies/ASP.NET-MVC/Exam/ForumSystem-master/Source/Web/ForumSystem.Web/Views/Home/Index.cshtml
@model IEnumerable<ForumSystem.Web.ViewModels.Home.IndexBlogPostViewModel>
@{
    ViewBag.Title = "Home Page";
    var ajaxOptions = new AjaxOptions()
    {
        UpdateTargetId = "votes",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST"
    };
}

@*@using (Ajax.BeginForm("PostVote", "Votes", ajaxOptions))
    {*@
<div class="container">
    @foreach (var post in Model)
    {
        <div class="row">
            <div class="col-md-2">
                <div class="well text-center">
                    <div class="row"><input type="submit" id="voteUp" value="Up" /> 0</div>
                    <div class="row"><input type="submit" id="voteDown" value="Down" /> votes</div>
                </div>
            </div>
            <div class="col-md-1">
                <div class="well text-center">
                    <div class="row">0</div>
                    <div class="row">answers</div>
                </div>
            </div>
            <div class="col-md-9">
                <div class="row">
                    <h4>
                        <a href="/questions/@post.Id/@post.Title">@post.Title</a>
                    </h4>
                </div>
                <div class="row">
                    <p>asked @((System.DateTime.Now - post.CreatedOn).Minutes) minutes ago in <a href="#">Category.Name</a> by <a href="#">@(post.Author.UserName)</a> (40 points)</p>
                </div>
                <div class="row">
                    @foreach (var tag in post.Tags)
                    {
                        <span class="label label-default">@tag.Name</span>
                    }
                </div>
            </div>
        </div>
        <hr />
    }
</div>
@*}*@